clone_vm_id = 993
cores       = 4
sockets     = 1
cpu_type    = "host"
memory      = 6144
net_model   = "e1000"
net_bridge  = "vmbr0"
vm_tags     = ["monitoring", "ubuntu", "terraform"]
zakres      = "all"
